### PR TITLE
Collection implementation

### PR DESCRIPTION
**Pull request by Simply007**
### Motivation

#91

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by Simply007** [comment]
Build filed cause - same as here: https://github.com/dbwebb-se/ramverk1/issues/13#issue-755375574

**Review by petrsvihlik — APPROVED** [review]

**Comment by petrsvihlik** [comment]
the https://github.com/xdebug/xdebug/pull/699 has already been released in https://github.com/xdebug/xdebug/releases/tag/3.0.1

what can we do to start using it? (update travis.yml or hardcode that dependency in composer.json?)

**Comment by petrsvihlik** [comment]
don't forget to create an appropriate PR in 
- [ ] @Simply007 https://github.com/KenticoDocs/kontent-docs-samples/tree/master/php

**Comment by Simply007** [comment]
I might have found a solution here: https://travis-ci.community/t/xdebug-3-is-installed-by-default-breaking-builds/10748/3

Setting XDEBUG_MODE=coverage should do the trick in travis configuration

**Pull request merged**
